### ISSUE TITLE
Cannot install threejs

### ISSUE THREAD

**Issue by ArthurZ** [bwlewis/rthreejs#12]
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called 'maps'
ERROR: lazy loading failed for package 'threejs'
removing 'C:/Analytics/R/R-3.1.1/library/threejs'
Error: Command failed (1)

**Comment by bwlewis** [comment]
I will fix this missing dependency issue (and make it optional), sorry for the latency.

For now, first run:

install.packages("maps")

**Comment by bwlewis** [comment]
Should be resolved now in commit https://github.com/bwlewis/rthreejs/commit/4fa9c619a0fe7d2d5f064d9c383f40ee18d88f89
