### ISSUE TITLE
d3 frameworl

### ISSUE THREAD

**Issue by AndreasBriese** [bwlewis/rthreejs#16]

**Comment by AndreasBriese** [comment]
d3 framework isn't essential to scatterplotThree.js and can be replaced by pure javascript and the dependency in scatterThree.yaml may be deleted.

  el.innerHTML = "";
  el.appendChild(r.domElement);
  var coordLabel = document.createElement("div");
  coordLabel.setAttribute("id","coordinate_label");
  coordLabel.style.zIndex = "100";
  coordLabel.style.position = "absolute";
  coordLabel.style.top = "0";
  coordLabel.style.margin = labelmargin;
  el.appendChild(coordLabel);

//   d3.select(el).node().innerHTML="";
//   d3.select(el).node().appendChild(r.domElement);
//   d3.select(el).append("div").text(" ").attr("id","coordinate_label");
//   document.getElementById("coordinate_label").style.zIndex = "100";
//   document.getElementById("coordinate_label").style.position = "absolute";
//   document.getElementById("coordinate_label").style.top = "0";
//   document.getElementById("coordinate_label").style.margin = labelmargin;

**Comment by bwlewis** [comment]
Dear Andreas, thank you! This is really valuable. Would you like to send me a pull request? Or would you prefer that I make the changes you suggest? Your call.

Kind regards,

Bryan

**Comment by AndreasBriese** [comment]
Hi Bryan,

i have forked the repo and made my changes at my local repo of the fork - i will change some more to improve performance and streamline scatterplotThree.js for my slightly different context.

Therefore i guess, best will be you do the changes directly at the master. I will keep you updated if i find further useful changes for rThreejs.

All the best
Andreas

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
eduToolbox@Bri-C GmbH
Auf der Bleiche 2a
31157 Sarstedt
Bevollmächtigter Geschäftsführer
Dr. med. vet. Andreas Briese
Fachtierarzt f. Tierhygiene /  Veterinary Specialist for Animal Hygiene
Fachtierarzt f. Tierschutzkunde /  Veterinary Specialist for Animal Welfare Sciences
Landesbeauftragter für den Tierschutz des Landes Niedersachsen a. D.
O2mobil: ++49 (0)176 623 537 89
Festnetz: ++49 (0)5066 695 92 14
Fax: ++49 (0)5066 695 82 18
E-Mail: info@eduToolbox.de, ab@bri-c.de 
WWW: http://edutoolbox.de
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
This message is intended exclusively for the addressee. It may contain
information that is confidential. Any use or publication of this
e-mail message without permission of the sender is not allowed. If you
are not the intended recipient, please notify us and delete this
message.



Am 21.05.2015 um 17:16 schrieb B. W. Lewis <notifications@github.com>:

**Comment by bwlewis** [comment]
I merged your master just now. Thanks for this!

Look forward to more collaboration...

Best,

Bryan

**Comment by AndreasBriese** [comment]
Hi Bryan,

though you might be interested in what i have used your code for:

http://oo8.eu

These are analysis results from a rat tracking algorithm i work on these days in an 1mx1m arena after different treatments (see the link to London imperial college at the site’s fouter). I found the 3D representation much more suitable to understand the differences between the individual rats. (switch between rats by clicking at the red button on the very right side)

I have done some further changes to your script to improve performance: one related the particle charging for-loops and one regarding the format of data.x.data  - will upload these to github and comment on in the next days.

Mit freundlichen Grüßen
Andreas Briese

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Bri-C Veterinärinstitut GbR
Auf der Bleiche 2a
31157 Sarstedt
Dr. med. vet. Andreas Briese
Landesbeauftragter für den Tierschutz des Landes Niedersachsen a. D.
FTA Tierschutzkunde, FTA Tierhygiene
O2mobil: ++49 (0)176 623 537 89
Festnetz: ++49 (0)5066 603970
Fax: ++49 (0)5066 695 82 18
E-Mail: info@eduToolbox.de, ab@bri-c.de
WWW: http://bri-c.de, http://edutoolbox.de
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
This message is intended exclusively for the addressee. It may contain
information that is confidential. Any use or publication of this
e-mail message without permission of the sender is not allowed. If you
are not the intended recipient, please notify us and delete this
message.



Am 21.05.2015 um 18:26 schrieb B. W. Lewis <notifications@github.com>:
