### ISSUE TITLE
NA Values Breaking Scatterplot3js

### ISSUE THREAD

**Issue by jamesa8** [bwlewis/rthreejs#20]
I am attempting to plot some data that has certain points that are NA. In scatterplot3d this functionality is supported by ignoring values that are NA. If the point were to be c(5,5, NA) the graph will plot the value as c(5,5,0).  Currently, Scatterplot3js doesn't have this capability. If you attempt to use an NA value then you receive the following: 

"Error in seq.default(from = mn[1], to = mx[1], length.out = num.ticks[1]) : 
  'from' cannot be NA, NaN or infinite"

Obviously this isn't a terribly urgent issue. I have already found a work around to this by just assigning my NA values to 0. However, I feel that this addition to the library would be helpful and would remove some unnecessary code. 

Here is an example of what I mean.
a<- c(NA , 1 , 1 , 1)
b<- c(NA, NA, 2, 3)
c<- c(NA, 3,  2, 2)
scatterplot3d(a,b,c) #This code provides a plot
scatterplot3js(x=as.matrix(data.frame(a,b,c)),  size=1, pch = 0.2) #this code breaks

Thanks for your time, 

Amber

**Comment by bwlewis** [comment]
Good catch! Thanks!

Note that scatterplot3d, like most other plot functions in R, doesn't set the missing values to zero, but rather omits them from the plot.

I've updated scatterplot3js to do this too. You can test it by installing the development version from github (if you don't have the devtools package, first install that from CRAN with install.packages("devtools"):

devtools::install_github("bwlewis/rthreejs")

Then your example should work and plot the two points that have all non-missing coordinates:

```{r}
library(scatterplot3d)
library(threejs)
a <- c(NA , 1 , 1 , 1)
b <- c(NA, NA, 2, 3)
c <- c(NA, 3, 2, 2)
scatterplot3d(a,b,c)
scatterplot3js(a,b,c,  size=1)
```

Note also in your original example that the `pch` option is ignored right now in scatterplot3js. Someday it will support point glyphs but not yet...

**Comment by jamesa8** [comment]
Wow, that was super fast. Thanks so much!

**Comment by bwlewis** [comment]
I'm closing this...re-open it if it's not working for you.
