### ISSUE TITLE
Fix R code for globejs.Rd

### ISSUE THREAD

**Issue by chendaniely** [bwlewis/rthreejs#21]
Lines 90 and 96 in the globejs.Rd have a slash that R tries to escape but can't, the slash should be removed:

from:
`dest   <- factor(sprintf("\%.2f:\%.2f",flights[,3], flights[,4]))`
to:
`dest   <- factor(sprintf("%.2f:%.2f",flights[,3], flights[,4]))`

and
from:
`idx <- dest \%in\% frequent_destinations`
to:
`idx <- dest %in% frequent_destinations`

Not sure if the slash is there to escape from the .Rd document, but it shows up on the website [1],
and will not copy/paste as is.  It seems you might have the escape sequence there for a reason, so
a PR to remove it might break things?

[1] http://bwlewis.github.io/rthreejs/globe/index.html

**Comment by bwlewis** [comment]
Hmmm. I see that and it's an interesting artifact. I didn't write the globejs.Rd file--it was auto-generated by roxygen2 (from the doc in the globejs.R function itself).

So, you're right don't issue a PR because that file is just auto-generated anyway.

I'll investigate and respond when I figure out why the slashes are there.

**Comment by chendaniely** [comment]
So apparently this was an issue ~ 5 years ago [1], but there wasn't any followup in the comments to be useful.  It does seem to be a roxygen/roxygen2 issue [2]


[1] http://stackoverflow.com/questions/2566128/how-to-escape-in-roxygen-literate-programming
[2] https://github.com/klutometis/roxygen/issues/313

**Comment by bwlewis** [comment]
Actually, the slash is correct. See, for example the discussion here:
http://cran.r-project.org/doc/manuals/r-release/R-exts.html#Insertions

Notice that the text renders properly in the R help system when running
?globejs

The fact that it's on the website is a lazy copy and paste error on my part. I'll fix that, sorry!
