### ISSUE TITLE
Plot is not re-created when changing data from server.R?

### ISSUE THREAD

**Issue by stefano-meschiari** [bwlewis/rthreejs#23]
First of all, great work, this could shape up to be really awesome!

I'm trying to use it for a little interactive visualization of known exoplanet candidates made with Shiny. The 3D scatter plot is generated OK during the first pass. It seems that when I change the data in server.R based on the UI changes, the plot generated by renderScatterplotThree is not being recreated (looking at the DOM, there's a 0x0px canvas instead).

The code is extremely simple, here:
https://github.com/stefano-meschiari/Planet-Discoveries/blob/with-scatter3js/server.R

and here's it running on shinyapps.io:
https://stefano-meschiari.shinyapps.io/PlanetPlot-threejs

**Comment by bwlewis** [comment]
Thanks for this, working on it. I think it might be related to:

https://github.com/ramnathv/htmlwidgets/issues/129

**Comment by bwlewis** [comment]
I was wrong, it was an unrelated bug. Try it now, first run:

devtools::install_github("bwlewis/threejs")

**Comment by stefano-meschiari** [comment]
Great, works now!

**Comment by bwlewis** [comment]
Excellent, closing this.

FYI, you can add mouse-over labels to the points too, see the 'labels' option.
