### ISSUE TITLE
15756 warnings on console in example and slow to appear

### ISSUE THREAD

**Issue by TimBock** [bwlewis/rthreejs#28]
- Open Google Chrome and the devtools.
- Navigate to http://bwlewis.github.io/rthreejs/bling/index.html
- Observe that it takes a long time for the globe to appear, and finally the console shows:

```
THREE.WebGLRenderer 70
15756 three.min.js:612 THREE.GeometryUtils: .merge() has been moved to Geometry. Use geometry.merge( geometry2, matrix, materialIndexOffset ) instead.
```

I am hoping once the warning is fixed, this will make the globe appear quicker (because a particular data set I am using is taking a much longer time to show the globe, and has the same symptoms).

Let me know if there's anything I can do to help.

**Comment by bwlewis** [comment]
Sorry for the long latency. Working on a fix now. See issue #30. I should have something ready later this week.

**Comment by bwlewis** [comment]
If this is still an issue with the current package version 0.3.0, please re-open.
