### ISSUE TITLE
The 'size' argument is ignored with "webgl" renderer when using 'points3d()' to add points. 

### ISSUE THREAD

**Issue by bkostadi** [bwlewis/rthreejs#37]
```
n<-300
z <- seq(-10, 10, length.out = n)
x <- cos(z)
y <- sin(z)
obj<-scatterplot3js(x,y,z, size=0.3,color=rainbow(length(z)), labels="Points",renderer = "webgl") 
obj$points3d(rnorm(n),rnorm(n),rnorm(n),size=0.1)

# the 'size' argument is ignored with "webgl" renderer
# the "canvas" renderer works fine with 'size' but it is too slow for thousands of points
```

**Comment by bwlewis** [comment]
Yes, this is documented in ?scatterplot3js:

>    size: The plot point radius, either as a single number or a vector
>           of sizes of length ‘nrow(x)’. A vector of sizes is only
>           supported by the ‘canvas’ renderer. The ‘webgl’ renderer
>           accepts a single size value for all points.
> 

However, others have been working on ways to support this in webGL but it's not quite finished yet. See, for example:

https://github.com/bwlewis/rthreejs/issues/33

**Comment by bkostadi** [comment]
The real problem is that while webgl accepts a single size value for all points, this works only if you don't try to add points using points3d. In the example I posted, I was trying to add points using points3d and then webgl does not work with a single size value for all points. It simply ignores it. Is that not a bug?

**Comment by bwlewis** [comment]
Not a bug, it's expected. The webGL renderer only supports a single point size right now. When you add points, the plot is re-rendered and all the points use the newly specified point size.

See the discusssion in issue #33 for an experimental alternate approach that is more general. Wer're working on that now...

**Comment by bkostadi** [comment]
Thanks for the prompt response! I love the potential that the rthreejs package offers for developing educational projects and I am very happy that you are actively working on it. I'll try to implement the experimental approach.
