### ISSUE TITLE
point of rotation of scatterplot3js cube

### ISSUE THREAD

**Issue by antonkratz** [bwlewis/rthreejs#38]
Very promising package, I am using scatterplot3js in Shiny. I seem to be only able to rotate the 3D scatterplot cube around the origin. I would like to rotate it around another point (the center of the cube). The way it is now, I find it very confusing to rotate because the cube changes size because of the perspective, and especially some angles are difficult to inspect, i.e. when I want to look from the top down, I have to rotate the cube away from me, and everything gets very small, and zooming in doesn't really help.
Is it possible to roate the scatterplot cube around it's center? If not, could this be implemented?

**Comment by bwlewis** [comment]
Dear Anton,

Thanks for these comments. In short I agree and, yes I think this is possible! I've been mulling over ways to make the scatterplot work more like the network plots, which rotate and pan much more naturally, see: http://bwlewis.github.io/rthreejs/graphjs.html  or `?graphjs` from the R package.

One issue with that that I need to figure out that makes this a bit longer and harder than it seems is I feel that it's important to preserve the scatterplot function for canvas render targets to support non-web-GL enabled browsers or devices. Unfortunately that other rotation scheme isn't working with canvas yet.

Anyway, I will try to make this happen, but it might take a little while (there is also a queue of other projects in front of this for me at the moment).

If you (or anyone) feels up to trying to adapt the graphjs rotation scheme, please feel free to hack on this!

Best,

Bryan

**Comment by bwlewis** [comment]
OK, this is now greatly improved. Try it out (version 0.3.0, not yet on CRAN).
