### ISSUE TITLE
scatterplot3js in threejs_0.3.0 is not interactive

### ISSUE THREAD

**Issue by sargdavid** [bwlewis/rthreejs#48]
I'm having issues with version 0.3.0. My plots are static: I cannot rotate them, and hovering over does not show the values. I tried to plot in both, RStudio Desktop and Server; in both cases I get the same result. 
Thank you.

**Comment by bwlewis** [comment]
Can you supply:

R version, RStudio version, operating system, type of interface (touch, mouse, trackpad, etc.)?

**Comment by bwlewis** [comment]
Try re-installing from GitHub:

```{r}
devtools::install_github("bwlewis/rthreejs")
```
there was a bug in the cavas renderer that maybe you ran in to (although hopefully you have OpenGL available which works much better)

**Comment by sargdavid** [comment]
Thank you very much, it worked! The movements are a lot smoother now and control feels more natural.

Going back to Issue #49, could you please explain me how to change the center of rotation (Issue #49 has been otherwise closed by you because it was about this functionality in version 0.2.2)

Thank you.

**Comment by bwlewis** [comment]
try panning first, then rotating

**Comment by sargdavid** [comment]
That's good enough. Thank you Brian. I'm closing this issue.
