### ISSUE TITLE
scatterplot3js in threejs_0.2.2 only rotates about the origin

### ISSUE THREAD

**Issue by sargdavid** [bwlewis/rthreejs#49]
Is there a way to change the center of rotation for a 3D scatterplot in threejs? I heard you showed an updated version of the package at the RStudio conference but I am unable to reproduce this feature.

Thank you.

**Comment by bwlewis** [comment]
Yes, better pan/zoom/rotate control is supported in the development version 0.3.0.

**Comment by sargdavid** [comment]
Thank you!
