### ISSUE TITLE
shiny support for graphjs

### ISSUE THREAD

**Issue by grepinsight** [bwlewis/rthreejs#51]
Hi, 

I saw your talk on rstudioconf::2017, and `threejs::graphjs()` looks awesome! Thank you.

I wanted to use  `threejs::graphjs()` on shiny, but it seems that there is no shiny output function for `graphjs` like the ones for `globe` and `scatterplot3d`?

- threejs::globeOutput()
- threejs::scatterplotThreeOutput()

**Comment by bwlewis** [comment]
Sorry, I forgot to add that in! I'm in the middle of fixing an issue with the current development version, and then will add an example right after that.

**Comment by shotchki** [comment]
This issue was closed two years ago but I cannot find an example of how to render graphs in shiny anywhere. Please can you point me in the right direction?

**Comment by cbail** [comment]
Thanks for the wonderful package! Any update on shiny bindings? I see in the latest documentation that there is support for globe and 3d scatterplot but not graphjs. If one does not yet exist, any tips on how to create one? Thank you.
