### ISSUE TITLE
showLabels issue and variable edge width

### ISSUE THREAD

**Issue by SundareshPrasanna** [bwlewis/rthreejs#54]
Hey Lewis thanks for this amazing package. I am facing some difficulties with showing vertex labels by default and not needing to hover over them individually.
I am also trying to achieve variable node width based on a weight or a third parameter can you please help me on both of them.

please find the sample code below:

graphjs(gdf, main="3-D Analysis", 
        vertex.label = V(gdf)$name, opacity=0.6, curvature=0.5, showLabels=T,
        edge.width = (0.05*E(gdf)$Count), edge.color = "grey", stroke=F)

where gdf is a igraph object :    **gdf <- graph.data.frame(df, directed = F)**

**Comment by bwlewis** [comment]
Unfortunately, I think some of what you ask for is not supported. I will try to make this more clear in the documentation ?graphjs.

- For performance and technical reasons, the current version here on GitHub (0.3.0) only supports uniform edge widths (a warning is generated when multiple edge widths are specified).
- Vertex labels are only mouse over. Alternatively you may use vertex.shape to plot character names, see the examples:

```r
library(threejs)
data("LeMis")
(graphjs(LeMis, vertex.shape=V(LeMis)$label))
```

If you would like to contribute and add the features, please do! The edge width issue is a concession to performance for large-scale networks. I don't think that it's easy to support but I could be wrong.
