### ISSUE TITLE
revealjs hacks

### ISSUE THREAD

**Issue by bwlewis** [bwlewis/rthreejs#60]
Hey, @ramnathv   @jjallaire  

I put this hack in to support revealjs and rmarkdown: 

https://github.com/bwlewis/rthreejs/blob/master/inst/htmlwidgets/scatterplotThree.js#L156

First I check to see if jQuery exists, if not I use addEventListener.  But that didn't seem to work so well, for reveal so I added 

https://github.com/bwlewis/rthreejs/blob/master/inst/htmlwidgets/scatterplotThree.js#L156

which works, but incurs extra rendering.

My question is, what is the right way to use addEventListener for slide changes in rmarkdown without needing to add the bloat of a jQuery library?

thanks!

**Comment by jjallaire** [comment]
I'd just include jquery. The default reveal.js presentation (containing one
plot + embedded libraries) is 1.3MB on my system. Adding jquery still
reports it as 1.3MB (it's 93K).

**Comment by bwlewis** [comment]
OK, thanks.  Is there a possibility of jquery version conflicts between
widgets?  jquery seems like it has global state.

**Comment by jjallaire** [comment]
html dependencies are shared (i.e. when you use one named "jquery" it's
guaranteed there will be only one "jquery" dependency, the one provided
that has the most recent version). So no problem with conflicts.

Also, if you are in an htlml_document, ioslides_presentation, or any Shiny
application you will already have jquery so there is no extra cost to the
dependency.

**Comment by bwlewis** [comment]
Done.  Thanks for your help!
