### ISSUE TITLE
Example vertex click Question

### ISSUE THREAD

**Issue by jzicker** [bwlewis/rthreejs#62]
I've seen other interactive graphs with the behavior of clicking on a vertex highlights that vertex and it's one edge away neighbors while de-emphasizing all not connected or connected farther down the path vertices.    Do you know of an example using rthreejs for this?

**Comment by bwlewis** [comment]
no, but I've heard this request from someone else.

this should be added as a feature request issue...

**Comment by bwlewis** [comment]
Try the latest master branch commit out--use the brush=TRUE option to support highlighting a clicked vertex and connected edges.

I fixed lots of edge-case bugs with animation that might also help your other issue #63 .
