### ISSUE TITLE
lines3d apparently does not work

### ISSUE THREAD

**Issue by ugroempi** [bwlewis/rthreejs#73]
Thank you for providing threejs. I very much like the appearance of the scatter plots. However, I haven't been able to add lines, and the example from the lines3d documentation does not work (error message:

`Error in xyz.coords(x, y, z, recycle = TRUE) : `
  `(list) object cannot be coerced to type 'double'`)

Best, Urike

**Comment by bwlewis** [comment]
thanks, I'm pretty sure you've spotted a bug and i have an idea how to fix
it.

i am away for the weekend but will try to fix soon...

**Comment by bwlewis** [comment]
Sorry for the long latency, I obviously got side-tracked.  I thought I had figured out your issue but now I can't reproduce it. When I run the example from `?lines3d`:

```{r}
x <- rnorm(5)
y <- rnorm(5)
z <- rnorm(5)
scatterplot3js(x, y, z, pch="@", color=rainbow(5)) %>% lines3d(c(1, 2), c(3, 4), lwd=2)
```
I get the scatterplot (with lines):

![image](https://user-images.githubusercontent.com/142494/35609428-4491a988-062b-11e8-9550-a2855a8d0ff9.png)

**Comment by ugroempi** [comment]
So apparently some things can be waited out ... It now works for me as well.
Best, Ulrike
