### ISSUE TITLE
troubles seeing output of `scatterplot3js()`

### ISSUE THREAD

**Issue by homerhanumat** [bwlewis/rthreejs#8]
This looks like a very promsing package!

Two things I notice:

* Output of `scatterplot3js()` won't show on a standalone .html.
* On R Studio desktop, the output shows up fine, when previewed either in the Viewer Pane or in a separate Window.  However, on the Server, in either mode you lose the output as soon as you scroll.

My version information:

* Desktop:  v0.98.1091, Ubuntu
* Server:  v0.98.1085, Ubuntu
* Browser:  latest Firefox

My session info on the server:

```
> sessionInfo()
R version 3.1.2 (2014-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)

locale:
 [1] LC_CTYPE=en_US.UTF-8 LC_NUMERIC=C         LC_TIME=C            LC_COLLATE=C        
 [5] LC_MONETARY=C        LC_MESSAGES=C        LC_PAPER=C           LC_NAME=C           
 [9] LC_ADDRESS=C         LC_TELEPHONE=C       LC_MEASUREMENT=C     LC_IDENTIFICATION=C 

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] digest_0.6.4     htmltools_0.2.6  rmarkdown_0.3.10 tools_3.1.2      yaml_2.1.13   
```

Some test code:

```
library(threejs)
library(plyr)

x <- iris$Sepal.Length
y <- iris$Sepal.Width
z <- iris$Petal.Length
dataIris <- cbind(x,y,z)
colnames(dataIris) <- c("sepLen","sepWid","petLen")
col <- mapvalues(iris$Species,
                 from=unique(iris$Species),
                 to=c("red","blue","green"))
scatterplot3js(dataIris, color=col,flip.y=FALSE)
```

Let me know if I can provide more information.

Regards,
Homer

**Comment by bwlewis** [comment]
I know this has been a while, but lots of improvements have been put in place in the last month fixing a number of Firefox-specific issues in particular. Maybe try again with the latest version, or test a few canned examples from the doc here:

http://bwlewis.github.io/rthreejs

**Comment by bwlewis** [comment]
I think that I've resolve these problems. Try using the CRAN version; it's working for me on Firefox now. If you still run into problems, please re-open!
