### ISSUE TITLE
Missing library load in the README.md examples

### ISSUE THREAD

**Issue by antononcube** [bwlewis/rthreejs#91]
Hi!
Great package! I think it is better if the README.md of the GitHub project includes a library loading command. For example,

```
library(threejs)
z <- seq(-10, 10, 0.1)
x <- cos(z)
y <- sin(z)
threejs::scatterplot3js(x, y, z, color=rainbow(length(z)))
```

**Comment by bwlewis** [comment]
Thanks! I agree, it's done.

**Comment by bwlewis** [comment]
p.s. if the `library(threejs)`  is used, then the namespace scope `threejs::` is redundant.
