### ISSUE TITLE
Hierarchical layouts

### ISSUE THREAD

**Issue by wlandau** [bwlewis/rthreejs#94]
`rthreejs` produces amazing visuals, and I am considering it for a possible extension to [`targets`](https://docs.ropensci.org/targets/). `targets` produces hierarchically-arranged directed acyclic graphs like the ones shown at the top of [this chapter](https://books.ropensci.org/targets/hpc.html) (using the current `visNetwork` backend). Is there a way to arrange `rthreejs` graphs so all the edges point in the general right-hand direction? This is important for understanding the overall flow of `targets`-powered data analysis pipelines.

**Comment by bwlewis** [comment]
Only partially...

1. There is no direction indicator on the edges. I have previously been
unable to find a threejs way to support this and also yield high
performance rendering of huge graphs (a key objective of the package).
I'll look again at threejs to see if something new came along to help this,
or see if I can come up with another approach. Adding directed graph
visualization support is a long desired option. But again maybe not
compatible with performance.

2. the left to right layout in your example (subject to rotation of course)
should be possible, but maybe not so obvious to implement. The current
layouts are now mostly just igraph package layouts, but the vertices are
just 3d Cartesian coordinates under the hood.  Of course a planar layout is
rather unexciting in 3d, but it can be accomplished i think.

I'll work out an example of #2.  Maybe that can become a vignette (adding
new layouts).

Best,

Bryan

**Comment by bwlewis** [comment]
p.s.  Also, those visNetwork plots are very cool as is!

**Comment by bwlewis** [comment]
Here is a rather lame example of explicit use of the layout. Your visNetwork plots look much cooler.

```{r}
library(threejs)

# Set up example adjacency matrix
adj <- matrix(0,5,5)
colnames(adj) <- c("data", "fast_fit", "plot_1", "slow_fit", "plot_2")
adj[1,2] <- adj[1,4] <- adj[2,3] <- adj[4,5] <- 1

# Create a 3-d layout for the vertices
layout <- matrix(0,5,3)
layout[2,] < -c(1,1,0.5)
layout[3,] <- c(2,1,0.5)
layout[4,] <- c(1,-1,-0.5)
layout[5,] <- c(2,-1,-0.5)

graphjs(graph_from_adjacency_matrix(adj),  layout=layout) %>%
  points3d(vertices(.)[[1]]  - cbind(0, rep(0.25, 5), 0) , color=4, pch=colnames(adj), size=0.5)

# The points3d(...  adds text labels to the graph. vertices(.)[[1]] indicates
# the 1st set of vertices (that is, not an animation where more than one set of
# vertices exist).  The cbind(0, rep(0.25.5), 0) is a 3-column matrix of 5 rows
# that offsets the labels from each vertex slightly.
```

IMO stick with visNetwork unless you've got a huge number of vertices to plot.

**Comment by wlandau** [comment]
Thanks for exploring this. The third visual dimension does seem like it could be useful for huge graphs, though I am not sure I could manually come up with a useful set of coordinates in the general case.
